[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.17.0"

[[constraint]]
  name = "github.com/julienschmidt/httprouter"
  version = "1.2.0"

[[constraint]]
  name = "github.com/go-redis/redis"
  version = "6.15.3"

[prune]
  go-tests = true
  unused-packages = true
